import bcryptjs from "bcryptjs";
import { PrismaClient } from "@prisma/client";
import { fakerID_ID as faker } from "@faker-js/faker";
import { nuke } from "./nuke";
import { isErrored } from "stream";

console.log("🔌 connecting to the database");
const prisma = new PrismaClient();

// dataset generated by chat.openai.com
const SUBJECT_DATASET = [
  {
    title: "Bahasa Indonesia",
    materials: [
      "Menulis proposal",
      "Menulis teks prosedur",
      "Merancang gagasan paragraf",
      "Mencerna puisi klasikal",
      "Kaidah Tata Bahasa Indonesia",
      "Penggunaan Ejaan yang Benar",
      "Mengembangkan Karangan",
      "Membaca Sastra Indonesia",
      "Menulis Resensi Buku",
      "Mengenal Sastra Dunia",
      "Tata Bahasa dan Komunikasi",
    ],
  },
  {
    title: "Bahasa Inggris",
    materials: [
      "Tata Bahasa Inggris",
      "Membaca Pemahaman",
      "Menulis Esai",
      "Latihan Berbicara",
      "Kosakata Inggris",
      "Pengucapan",
      "Listening Skills",
      "Dialog Bahasa Inggris",
      "Kosa Kata Umum",
    ],
  },
  {
    title: "Matematika",
    materials: [
      "Aljabar",
      "Geometri",
      "Trigonometri",
      "Kalkulus",
      "Persamaan Matematika",
      "Integral",
      "Statistika",
      "Pecahan",
      "Peluang",
      "Derivatif",
    ],
  },
  {
    title: "Ilmu Pengetahuan Alam",
    materials: [
      "Dasar-dasar Biologi",
      "Fisika Dasar",
      "Kimia Dasar",
      "Ekologi",
      "Genetika",
      "Pemanasan Global",
      "Mikroorganisme",
      "Hukum Newton",
      "Reaksi Kimia",
      "Klasifikasi Makhluk Hidup",
    ],
  },
  {
    title: "Ilmu Pengetahuan Sosial",
    materials: [
      "Sejarah",
      "Geografi",
      "Ekonomi",
      "Kewarganegaraan",
      "Sosiologi",
      "Antropologi",
      "Psikologi Sosial",
      "Kebijakan Sosial",
      "Globalisasi",
      "Studi Perbandingan Masyarakat",
    ],
  },
  {
    title: "Sejarah",
    materials: [
      "Sejarah Dunia",
      "Sejarah Nasional",
      "Tokoh-tokoh Bersejarah",
      "Periode Sejarah",
      "Revolusi",
      "Kolonialisme",
      "Perang Dunia",
      "Imperialisme",
      "Masa Renaissance",
      "Purbakala",
    ],
  },
  {
    title: "Agama Islam",
    materials: [
      "Kepercayaan Islam",
      "Studi Al-Quran",
      "Sejarah Islam",
      "Filsafat Islam",
      "Hukum Islam",
      "Peradaban Islam",
      "Zaman Emas Islam",
      "Kebudayaan Islam",
      "Teologi Islam",
      "Pemikiran Islam",
    ],
  },
  {
    title: "PPKn",
    materials: [
      "Pendidikan Kewarganegaraan",
      "Sistem Pemerintahan",
      "Hak dan Kewajiban",
      "Undang-Undang Dasar",
      "Partisipasi Politik",
      "Politik Luar Negeri",
      "Konstitusi",
      "Demokrasi",
      "Pancasila",
      "Kebebasan Beragama",
    ],
  },
  {
    title: "Seni Budaya",
    materials: [
      "Seni Rupa",
      "Seni Pertunjukan",
      "Sejarah Seni",
      "Seni Modern",
      "Kesenian Tradisional",
      "Musik",
      "Seni Tari",
      "Seni Teater",
      "Seni Patung",
      "Seni Kinetik",
    ],
  },
  {
    title: "PJOK",
    materials: [
      "Pendidikan Jasmani",
      "Olahraga dan Permainan",
      "Kesehatan dan Kebugaran",
      "Teknik Dasar Olahraga",
      "Atletik",
      "Senam",
      "Permainan Bola",
      "Permainan Tradisional",
      "Renang",
      "Kebugaran Jasmani",
    ],
  },
  {
    title: "Biologi",
    materials: [
      "Biologi Sel",
      "Genetika",
      "Ekologi",
      "Mikrobiologi",
      "Anatomi Manusia",
      "Fisiologi",
      "Biologi Evolusioner",
      "Biologi Molekuler",
      "Biologi Perilaku",
      "Biologi Lingkungan",
    ],
  },
  {
    title: "Fisika",
    materials: [
      "Mekanika",
      "Listrik dan Magnetisme",
      "Termodinamika",
      "Optika",
      "Fisika Kuantum",
      "Fisika Nuklir",
      "Astronomi",
      "Geofisika",
      "Elektronika",
      "Teknik Fisika",
    ],
  },
  {
    title: "Kimia",
    materials: [
      "Reaksi Kimia",
      "Tabel Periodik",
      "Kimia Organik",
      "Kimia Anorganik",
      "Kimia Fisik",
      "Kimia Analitik",
      "Biokimia",
      "Kimia Lingkungan",
      "Kimia Farmasi",
      "Kimia Industri",
    ],
  },
  {
    title: "Geografi",
    materials: [
      "Geografi Fisik",
      "Geografi Manusia",
      "Studi Lingkungan",
      "Geografi Regional",
      "Kartografi",
      "Peta dan GIS",
      "Geopolitik",
      "Perubahan Iklim",
      "Bencana Alam",
      "Penginderaan Jauh",
    ],
  },
  {
    title: "Ekonomi",
    materials: [
      "Mikroekonomi",
      "Makroekonomi",
      "Kebijakan Ekonomi",
      "Ekonomi Internasional",
      "Ekonomi Pembangunan",
      "Ekonomi Moneter",
      "Ekonomi Perusahaan",
      "Ekonomi Keuangan",
      "Ekonomi Sumber Daya",
      "Ekonomi Lingkungan",
    ],
  },
  {
    title: "Sosiologi",
    materials: [
      "Teori Sosiologi",
      "Struktur Sosial",
      "Metode Penelitian",
      "Sosiologi Keluarga",
      "Sosiologi Pendidikan",
      "Sosiologi Agama",
      "Sosiologi Perubahan Sosial",
      "Sosiologi Kriminal",
      "Sosiologi Politik",
      "Sosiologi Ekonomi",
    ],
  },
  {
    title: "Antropologi",
    materials: [
      "Antropologi Budaya",
      "Antropologi Biologis",
      "Arkeologi",
      "Antropologi Sosial",
      "Antropologi Visual",
      "Antropologi Politik",
      "Antropologi Ekonomi",
      "Antropologi Medis",
      "Antropologi Hukum",
      "Antropologi Sejarah",
    ],
  },
];

const PASSWORD = "1234567890";

async function main() {
  const user = await prisma.user.create({
    data: {
      username: faker.internet.userName(),
      password: await bcryptjs.hash(PASSWORD, 12),
    },
  });

  console.log(`🌱 [I] username: ${user.username}, password: ${PASSWORD}`);
  prisma.subject.create({
    data: {
      title: "duarr",
      owner_username: user.username,
      materials: {
        createMany: {
          data: [
            {
              title: "s",
              owner_username: "asdasd",
            },
          ],
        },
      },
    },
  });

  await Promise.all(
    SUBJECT_DATASET.map((s) =>
      prisma.subject.create({
        data: {
          title: s.title,
          owner_username: user.username,
          materials: {
            createMany: {
              data:
                s.materials?.map((m) => ({
                  title: m,
                  owner_username: user.username,
                })) ?? [],
            },
          },
        },
      })
    )
  );
}

nuke()
  .then(() => console.log("💣 successfully nuked the database"))
  .then(() => main())
  .then(() => console.log("🌱 successfully seeded the database"))
  .finally(() => prisma.$disconnect());
